version: '3.7'

services:
  proxy:
    build:
      context: ./api/proxy
    #   command: npm start
    ports:
      - '4500:4500'
    environment:
      NODE_ENV: dev

  pocketbase:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pocketbase-data:/pb_data
volumes:
  pocketbase-data:
